# Generated by Django 3.2.12 on 2022-04-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='Register',
        ),
    ]
