# Generated by Django 3.2.12 on 2022-05-21 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20220408_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
        migrations.RemoveField(
            model_name='register',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='register',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
        migrations.RemoveField(
            model_name='register',
            name='phone',
        ),
        migrations.AddField(
            model_name='register',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='register',
            name='id_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='profile_pic',
            field=models.ImageField(default='tom-morbey-Ke_bXG4dc2w-unsplash.jpg', upload_to='profile_pic'),
        ),
        migrations.AddField(
            model_name='register',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
