# Generated by Django 3.2.12 on 2022-05-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220521_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
