# Generated by Django 3.2.12 on 2022-06-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220618_0050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
