# Generated by Django 3.2.12 on 2022-06-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_getdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getdatetime',
            name='date',
            field=models.TimeField(max_length=50),
        ),
    ]
