# Generated by Django 3.2.12 on 2022-06-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_getdatetime_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getdatetime',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
