# Generated by Django 3.2.12 on 2022-07-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booking_date',
            field=models.DateField(max_length=50, null=True),
        ),
    ]
