# Generated by Django 3.2.12 on 2022-07-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_bookings_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='user',
        ),
    ]
