# Generated by Django 3.2.12 on 2022-07-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_bookings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
