# Generated by Django 3.2.12 on 2022-07-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_bookings_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='bookingtime_finish',
            field=models.TimeField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='bookingtime_start',
            field=models.TimeField(max_length=50, null=True),
        ),
    ]
