# Generated by Django 3.2.12 on 2022-07-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20220728_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
