# Generated by Django 3.2.12 on 2022-08-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booking_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
